server:
  port: 18080
spring:
  datasource:
    url: jdbc:postgresql://25.2.6.144:5432/prptdb
    username: ifundrobot
    password: ENC(cR58FU/mdN/7ILRTL6VN3U74DQNJxAvL)
    driver-class-name: org.postgresql.Driver

  ai:
    model:
      embedding: yc
    openai:
      base-url: http://25.22.0.22:8080
      api-key: a66d12f370574bea8fcd3aa1e190ca5973c8a21130014f6ba5ba2ccd6676f8d9
      embedding:
        embeddingsPath: "/embeddings"
        enabled: true
        metadata-mode: EMBED
        options:
          model: Bge-m3-test
      chat:
        options:
          model: QWen2.5-32B
          internal-tool-execution-enabled: false
          httpHeaders:
            Authorization: "Bearer a66d12f370574bea8fcd3aa1e190ca5973c8a21130014f6ba5ba2ccd6676f8d9"
            sendSysOrCmptNo: "99370000000"
            startSysOrCmptNo: "99370000000"
            sceneId: "0288"
        completionsPath: /v1/chat/completions


yc:
  core:
    ai:
      resved-input-info: "0288"
      url: http://25.6.60.15:8000/online-service/rag/v1/
      send-sys-no: 99370000000
      target-sys-no: 99370000000
      embedding:
        enabled: true
      vector:
        enabled: true
        collection-name: pdf_inner_rule_index
        vector-field-name: embedding
      rerank:
        enabled: true


logging:
  level:
    com.psbc.cpecm_java_jdk1.7.0.65_lc_20240909_hefei-langfang: error
    root: info

mpda:
  rerank:
    enabled: false
    base-url: http://25.22.0.22:8080
    api-key: a66d12f370574bea8fcd3aa1e190ca5973c8a21130014f6ba5ba2ccd6676f8d9
    rerankPath: "/rerank"
    model: bge-rerank-v2-m3
  contentManage:
    opeSysId: 99370000000
    byOpeSysId: 99711870000
    location: 1
    #  areaCode: 98--定版环境 01--预演环境 99-生产环境 T2-t2环境
    areaCode: "99"
    fileSavePath: "./ai-bot/fileTemp"
    opeType: T01302
    opeUser: 20080733650
    opeOrg: 11005293


