server:
  port: 18080

#mpda:
#  scene:
#    retry: 1
#    common:
#      enabled: true
#    strategy: plan

spring:
  application:
    name: ai-code

  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: 
      chat:
        options:
          model: qwen-plus
          internal-tool-execution-enabled: false

#    mcp:
#      client:
#        enabled: true
#        sse:
#          connections:
#            playwright:
#              url: http://localhost:8931
#              sse-endpoint: /sse
#        stdio:
#          connections:
#            postgres:
#              command: docker
#              args:
#                - run
#                - -i
#                - --rm
#                - -e
#                - DATABASE_URI
#                - crystaldba/postgres-mcp
#                - --access-mode=unrestricted
#              env:
#                DATABASE_URI: postgresql://postgres:123456@172.23.35.20:5432/postgres
#            redis:
#              command: docker
#              args:
#                - run
#                - -i
#                - --rm
#                - -e
#                - REDIS_HOST
#                - -e
#                - REDIS_USERNAME
#                - -e
#                - REDIS_PORT
#                - -e
#                - REDIS_PWD
#                - -e
#                - REDIS_CLUSTER_MODE
#                - mcp/redis
#              env:
#                REDIS_HOST: 172.23.35.20
#                REDIS_USERNAME: ""
#                REDIS_PORT: 16379
#                REDIS_PWD: ""
#                REDIS_CLUSTER_MODE: False

mpda:
  monitor:
    persistence:
      enabled: true

logging:
  level:
    root: info
